### ISSUE TITLE
Error while building project

### ISSUE THREAD

**Issue by JayWebtech** [seena98/auto_start_flutter#13]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':auto_start_flutter'.
> Could not resolve all files for configuration ':auto_start_flutter:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.41.
     Required by:
         project :auto_start_flutter > com.android.tools.build:gradle:3.5.0
         project :auto_start_flutter > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0

**Comment by seena98** [comment]
Hi, released a new version, please let me know if you face any issues.
