### ISSUE TITLE
getting the issues while release build

### ISSUE THREAD

**Issue by sanakhan-cms** [seena98/auto_start_flutter#19]
uses or overrides a deprecated API.
C:\Users\AppData\Local\Pub\Cache\hosted\pub.dev\auto_start_flutter-0.1.1\android\src\main\java\co\techFlow\auto_start_flutter\AutoStartFlutterPlugin.java
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auto_start_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed

**Comment by seena98** [comment]
Hi, released a new version, please let me know if you face any issues.
