### ISSUE TITLE
Request: Update auto_start_flutter to support Flutter SDK 3.24.3 and Kotlin 1.9.24

### ISSUE THREAD

**Issue by EhabYasser1** [seena98/auto_start_flutter#21]
Hello,

Thank you for providing the auto_start_flutter package. I am currently using Flutter SDK 3.24.3 and Kotlin 1.9.24 in my project. However, I encountered issues when building APKs due to incompatibility with the latest SDK versions. The error occurs during the APK generation process.

Here are some suggestions for the update:
- Update `compileSdkVersion` and `targetSdkVersion` to 33 in the Android build.gradle file.
- Ensure compatibility with Gradle 8.0 and Android Gradle Plugin 8.0.
- Update Kotlin version to 1.9.24.

Could you please consider updating the package to support the latest versions? This would be highly beneficial for projects using modern Flutter and Kotlin versions.

Thank you!

**Comment by seena98** [comment]
Hi, I released a new version let me know if you have any issues
