### ISSUE TITLE
build note

### ISSUE THREAD

**Issue by amedeopro** [seena98/auto_start_flutter#8]
Hello,
when i build my app i receive this Note:

.pub-cache\hosted\pub.dartlang.org\auto_start_flutter-0.1.1\android\src\main\java\co\techFlow\auto_start_flutter\AutoStartFlutterPlugin.java uses or overrides a deprecated API.

How can i fix ?

**Comment by seena98** [comment]
Hi, released a new version, please let me know if you face any issues.
